apiVersion: v1
kind: Pod
metadata:
  name: test-init-container
spec:
  containers:
    - name: demo
      image: cloudnatived/demo:hello
      resources:
        limits:
          memory: 32Mi
          cpu: 50m
        requests:
          memory: 32Mi
          cpu: 50m
  initContainers:
    - name: init-demo
      image: busybox
      command: [sh, -c, echo Hello from initContainer]