apiVersion: v1
kind: Pod
metadata:
  name: test-empty-dir
spec:
  volumes:
  - name: cache-volume
    emptyDir: {}
  containers:
  - name: demo
    image: cloudnatived/demo:hello
    resources:
      limits:
        memory: 32Mi
        cpu: 50m
      requests:
        memory: 32Mi
        cpu: 50m
    volumeMounts:
    - mountPath: /cache
      name: cache-volume